export const patientProfileForm = {
  agePlaceholder: 'Ex: 45',
  professionPlaceholder: 'Ex: Pedreiro',
  weightPlaceholder: 'Ex: 75Kg',
  heightPlaceholder: 'Ex: 170',
  otherPlaceholder: 'Ex: Sedentário, alergias',
};

export const clinicalContentForm = {
  pedagogicalGoalPlaceholder: 'O que os alunos devem aprender...',
  centralHypothesisPlaceholder: 'Ex: Gripe, Resfriado, etc.',
  symptomsPlaceholder: 'Incluir histórico médico...',
  comorbiditiesPlaceholder: 'Adicionar comorbidades...',
  clinicalContextPlaceholder: 'Digite um contexto adicional relevante para o caso...',
};

export const referencesMediaUploads = [
  {
    title: 'Imagens Clínicas',
    description: 'Radiografias e fotos em PNG ou JPG.',
  },
  {
    title: 'Slides e/ou Material de Estudo',
    description: 'Arquivos em PDF, DOCX ou PPTX.',
  },
];

// Especialidades e áreas de atuação médicas reconhecidas pela Resolução CFM
// nº 2.380/2024, complementadas por áreas clínicas multiprofissionais.
const medicalSpecialties = [
  'Acupuntura',
  'Alergia e Imunologia',
  'Anestesiologia',
  'Angiologia',
  'Cardiologia',
  'Cirurgia Cardiovascular',
  'Cirurgia da Mão',
  'Cirurgia de Cabeça e Pescoço',
  'Cirurgia do Aparelho Digestivo',
  'Cirurgia Geral',
  'Cirurgia Oncológica',
  'Cirurgia Pediátrica',
  'Cirurgia Plástica',
  'Cirurgia Torácica',
  'Cirurgia Vascular',
  'Clínica Médica',
  'Coloproctologia',
  'Dermatologia',
  'Endocrinologia e Metabologia',
  'Endoscopia',
  'Gastroenterologia',
  'Genética Médica',
  'Geriatria',
  'Ginecologia e Obstetrícia',
  'Hematologia e Hemoterapia',
  'Homeopatia',
  'Infectologia',
  'Mastologia',
  'Medicina de Emergência',
  'Medicina de Família e Comunidade',
  'Medicina do Trabalho',
  'Medicina do Tráfego',
  'Medicina Esportiva',
  'Medicina Física e Reabilitação',
  'Medicina Intensiva',
  'Medicina Legal e Perícia Médica',
  'Medicina Nuclear',
  'Medicina Preventiva e Social',
  'Nefrologia',
  'Neurocirurgia',
  'Neurologia',
  'Nutrologia',
  'Oftalmologia',
  'Oncologia Clínica',
  'Ortopedia e Traumatologia',
  'Otorrinolaringologia',
  'Patologia',
  'Patologia Clínica/Medicina Laboratorial',
  'Pediatria',
  'Pneumologia',
  'Psiquiatria',
  'Radiologia e Diagnóstico por Imagem',
  'Radioterapia',
  'Reumatologia',
  'Urologia',
];

const medicalPracticeAreas = [
  'Administração em Saúde',
  'Alergia e Imunologia Pediátrica',
  'Angiorradiologia e Cirurgia Endovascular',
  'Atendimento ao Queimado',
  'Auditoria Médica',
  'Cardiologia Pediátrica',
  'Cirurgia Bariátrica',
  'Cirurgia Crânio-Maxilo-Facial',
  'Cirurgia do Trauma',
  'Cirurgia Videolaparoscópica',
  'Citopatologia',
  'Densitometria Óssea',
  'Dor',
  'Ecocardiografia',
  'Ecografia Vascular com Doppler',
  'Eletrofisiologia Clínica Invasiva',
  'Emergência Pediátrica',
  'Endocrinologia Pediátrica',
  'Endoscopia Digestiva',
  'Endoscopia Ginecológica',
  'Endoscopia Respiratória',
  'Ergometria',
  'Estimulação Cardíaca Eletrônica Implantável',
  'Foniatria',
  'Gastroenterologia Pediátrica',
  'Hansenologia',
  'Hematologia e Hemoterapia Pediátrica',
  'Hemodinâmica e Cardiologia Intervencionista',
  'Hepatologia',
  'Infectologia Hospitalar',
  'Infectologia Pediátrica',
  'Mamografia',
  'Medicina Aeroespacial',
  'Medicina do Adolescente',
  'Medicina do Sono',
  'Medicina Fetal',
  'Medicina Intensiva Pediátrica',
  'Medicina Paliativa',
  'Medicina Tropical',
  'Nefrologia Pediátrica',
  'Neonatologia',
  'Neurofisiologia Clínica',
  'Neurologia Pediátrica',
  'Neurorradiologia',
  'Nutrição Parenteral e Enteral',
  'Nutrição Parenteral e Enteral Pediátrica',
  'Nutrologia Pediátrica',
  'Oncogenética',
  'Oncologia Pediátrica',
  'Pneumologia Pediátrica',
  'Psicogeriatria',
  'Psicoterapia',
  'Psiquiatria da Infância e Adolescência',
  'Psiquiatria Forense',
  'Radiologia Intervencionista e Angiorradiologia',
  'Reprodução Assistida',
  'Reumatologia Pediátrica',
  'Sexologia',
  'Toxicologia Médica',
  'Transplante de Medula Óssea',
  'Ultrassonografia em Ginecologia e Obstetrícia',
  'Ultrassonografia Geral',
];

const multiprofessionalClinicalAreas = [
  'Biomedicina',
  'Biomedicina Clínica',
  'Educação Física em Saúde',
  'Enfermagem',
  'Enfermagem Cardiovascular',
  'Enfermagem Dermatológica',
  'Enfermagem em Centro Cirúrgico',
  'Enfermagem em Estomaterapia',
  'Enfermagem em Nefrologia',
  'Enfermagem em Saúde da Família',
  'Enfermagem em Saúde Mental',
  'Enfermagem em Terapia Intensiva',
  'Enfermagem Obstétrica',
  'Enfermagem Oncológica',
  'Enfermagem Pediátrica e Neonatal',
  'Farmácia',
  'Farmácia Clínica e Hospitalar',
  'Fisioterapia',
  'Fisioterapia Aquática',
  'Fisioterapia Cardiovascular',
  'Fisioterapia Dermatofuncional',
  'Fisioterapia Esportiva',
  'Fisioterapia em Gerontologia',
  'Fisioterapia em Oncologia',
  'Fisioterapia em Osteopatia',
  'Fisioterapia em Quiropraxia',
  'Fisioterapia em Saúde da Mulher',
  'Fisioterapia em Terapia Intensiva',
  'Fisioterapia Neurofuncional',
  'Fisioterapia Respiratória',
  'Fisioterapia Traumato-Ortopédica',
  'Fonoaudiologia',
  'Fonoaudiologia em Audiologia',
  'Fonoaudiologia em Disfagia',
  'Fonoaudiologia em Gerontologia',
  'Fonoaudiologia Hospitalar',
  'Fonoaudiologia em Linguagem',
  'Fonoaudiologia em Motricidade Orofacial',
  'Fonoaudiologia Neurofuncional',
  'Fonoaudiologia em Saúde Coletiva',
  'Fonoaudiologia em Voz',
  'Nutrição',
  'Nutrição Clínica',
  'Nutrição em Esportes e Exercício',
  'Nutrição Materno-Infantil',
  'Nutrição Oncológica',
  'Odontologia',
  'Cirurgia e Traumatologia Bucomaxilofacial',
  'Dentística',
  'Disfunção Temporomandibular e Dor Orofacial',
  'Endodontia',
  'Estomatologia',
  'Implantodontia',
  'Odontogeriatria',
  'Odontologia Hospitalar',
  'Odontologia para Pacientes com Necessidades Especiais',
  'Odontopediatria',
  'Ortodontia',
  'Ortopedia Funcional dos Maxilares',
  'Patologia Oral e Maxilofacial',
  'Periodontia',
  'Prótese Dentária',
  'Radiologia Odontológica e Imaginologia',
  'Psicologia',
  'Psicologia Clínica',
  'Psicologia Hospitalar',
  'Psicologia em Saúde',
  'Psicologia em Saúde Mental',
  'Neuropsicologia',
  'Saúde Coletiva',
  'Serviço Social em Saúde',
  'Terapia Ocupacional',
  'Terapia Ocupacional em Contextos Hospitalares',
  'Terapia Ocupacional em Gerontologia',
  'Terapia Ocupacional em Saúde Mental',
];

export const healthSpecialties = [...new Set([
  ...medicalSpecialties,
  ...medicalPracticeAreas,
  ...multiprofessionalClinicalAreas,
])].sort((first, second) => first.localeCompare(second, 'pt-BR'));

export const selectOptions = {
  specialties: healthSpecialties,
  difficulties: ['Básico', 'Intermediário', 'Avançado'],
};

export const stepItems = [
  { label: 'Informações do caso', path: '/criar-caso/parametros' },
  { label: 'Perfil do Paciente', path: '/criar-caso/perfil-paciente' },
  { label: 'Conteúdo Clínico', path: '/criar-caso/conteudo-clinico' },
  { label: 'Referências e Mídias', path: '/criar-caso/referencias-midias' },
];
